apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sklearn-iris-monitor
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      networking.internal.knative.dev/serviceType: Private
  endpoints:
    - port: http-usermetric
      interval: 15s
